export const OPEN_CART_DIALOG_BOX = "OPEN_CART_DIALOG_BOX";
export const CLOSE_CART_DIALOG_BOX = "CLOSE_CART_DIALOG_BOX";
export const OPEN_ALERT_POPUP = "OPEN_ALERT_POPUP";
export const CLOSE_ALERT_POPUP = "CLOSE_ALERT_POPUP";
export const SAVE_CART = "SAVE_CART";